version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: connefut_db
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  pgweb:
    image: sosedoff/pgweb
    ports: 
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://root:password@db:5432/connefut_db?sslmode=disable
    depends_on:
      - db
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/app
    environment:
      TZ: 'Asia/Tokyo'
      GO_ENV: 'develop'
    tty: true
    links:
      - mailhog
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp
volumes:
  postgresql-data:
    driver: local
  maildir: