// Code generated by entc, DO NOT EDIT.

package recruitmenttag

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/nagokos/connefut_backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// RecruitmentID applies equality check predicate on the "recruitment_id" field. It's identical to RecruitmentIDEQ.
func RecruitmentID(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRecruitmentID), v))
	})
}

// TagID applies equality check predicate on the "tag_id" field. It's identical to TagIDEQ.
func TagID(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTagID), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RecruitmentTag {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RecruitmentTag {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RecruitmentTag {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RecruitmentTag {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// RecruitmentIDEQ applies the EQ predicate on the "recruitment_id" field.
func RecruitmentIDEQ(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRecruitmentID), v))
	})
}

// RecruitmentIDNEQ applies the NEQ predicate on the "recruitment_id" field.
func RecruitmentIDNEQ(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRecruitmentID), v))
	})
}

// RecruitmentIDIn applies the In predicate on the "recruitment_id" field.
func RecruitmentIDIn(vs ...string) predicate.RecruitmentTag {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldRecruitmentID), v...))
	})
}

// RecruitmentIDNotIn applies the NotIn predicate on the "recruitment_id" field.
func RecruitmentIDNotIn(vs ...string) predicate.RecruitmentTag {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldRecruitmentID), v...))
	})
}

// RecruitmentIDGT applies the GT predicate on the "recruitment_id" field.
func RecruitmentIDGT(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRecruitmentID), v))
	})
}

// RecruitmentIDGTE applies the GTE predicate on the "recruitment_id" field.
func RecruitmentIDGTE(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRecruitmentID), v))
	})
}

// RecruitmentIDLT applies the LT predicate on the "recruitment_id" field.
func RecruitmentIDLT(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRecruitmentID), v))
	})
}

// RecruitmentIDLTE applies the LTE predicate on the "recruitment_id" field.
func RecruitmentIDLTE(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRecruitmentID), v))
	})
}

// RecruitmentIDContains applies the Contains predicate on the "recruitment_id" field.
func RecruitmentIDContains(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldRecruitmentID), v))
	})
}

// RecruitmentIDHasPrefix applies the HasPrefix predicate on the "recruitment_id" field.
func RecruitmentIDHasPrefix(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldRecruitmentID), v))
	})
}

// RecruitmentIDHasSuffix applies the HasSuffix predicate on the "recruitment_id" field.
func RecruitmentIDHasSuffix(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldRecruitmentID), v))
	})
}

// RecruitmentIDEqualFold applies the EqualFold predicate on the "recruitment_id" field.
func RecruitmentIDEqualFold(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldRecruitmentID), v))
	})
}

// RecruitmentIDContainsFold applies the ContainsFold predicate on the "recruitment_id" field.
func RecruitmentIDContainsFold(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldRecruitmentID), v))
	})
}

// TagIDEQ applies the EQ predicate on the "tag_id" field.
func TagIDEQ(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTagID), v))
	})
}

// TagIDNEQ applies the NEQ predicate on the "tag_id" field.
func TagIDNEQ(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTagID), v))
	})
}

// TagIDIn applies the In predicate on the "tag_id" field.
func TagIDIn(vs ...string) predicate.RecruitmentTag {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTagID), v...))
	})
}

// TagIDNotIn applies the NotIn predicate on the "tag_id" field.
func TagIDNotIn(vs ...string) predicate.RecruitmentTag {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTagID), v...))
	})
}

// TagIDGT applies the GT predicate on the "tag_id" field.
func TagIDGT(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTagID), v))
	})
}

// TagIDGTE applies the GTE predicate on the "tag_id" field.
func TagIDGTE(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTagID), v))
	})
}

// TagIDLT applies the LT predicate on the "tag_id" field.
func TagIDLT(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTagID), v))
	})
}

// TagIDLTE applies the LTE predicate on the "tag_id" field.
func TagIDLTE(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTagID), v))
	})
}

// TagIDContains applies the Contains predicate on the "tag_id" field.
func TagIDContains(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTagID), v))
	})
}

// TagIDHasPrefix applies the HasPrefix predicate on the "tag_id" field.
func TagIDHasPrefix(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTagID), v))
	})
}

// TagIDHasSuffix applies the HasSuffix predicate on the "tag_id" field.
func TagIDHasSuffix(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTagID), v))
	})
}

// TagIDEqualFold applies the EqualFold predicate on the "tag_id" field.
func TagIDEqualFold(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTagID), v))
	})
}

// TagIDContainsFold applies the ContainsFold predicate on the "tag_id" field.
func TagIDContainsFold(v string) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTagID), v))
	})
}

// HasRecruitment applies the HasEdge predicate on the "recruitment" edge.
func HasRecruitment() predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RecruitmentTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RecruitmentTable, RecruitmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecruitmentWith applies the HasEdge predicate on the "recruitment" edge with a given conditions (other predicates).
func HasRecruitmentWith(preds ...predicate.Recruitment) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RecruitmentInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RecruitmentTable, RecruitmentColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTag applies the HasEdge predicate on the "tag" edge.
func HasTag() predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(TagTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TagTable, TagColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagWith applies the HasEdge predicate on the "tag" edge with a given conditions (other predicates).
func HasTagWith(preds ...predicate.Tag) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(TagInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TagTable, TagColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RecruitmentTag) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RecruitmentTag) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RecruitmentTag) predicate.RecruitmentTag {
	return predicate.RecruitmentTag(func(s *sql.Selector) {
		p(s.Not())
	})
}
