// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nagokos/connefut_backend/ent/applicant"
	"github.com/nagokos/connefut_backend/ent/recruitment"
	"github.com/nagokos/connefut_backend/ent/user"
)

// ApplicantCreate is the builder for creating a Applicant entity.
type ApplicantCreate struct {
	config
	mutation *ApplicantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (ac *ApplicantCreate) SetCreatedAt(t time.Time) *ApplicantCreate {
	ac.mutation.SetCreatedAt(t)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *ApplicantCreate) SetNillableCreatedAt(t *time.Time) *ApplicantCreate {
	if t != nil {
		ac.SetCreatedAt(*t)
	}
	return ac
}

// SetUpdatedAt sets the "updated_at" field.
func (ac *ApplicantCreate) SetUpdatedAt(t time.Time) *ApplicantCreate {
	ac.mutation.SetUpdatedAt(t)
	return ac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ac *ApplicantCreate) SetNillableUpdatedAt(t *time.Time) *ApplicantCreate {
	if t != nil {
		ac.SetUpdatedAt(*t)
	}
	return ac
}

// SetManagementStatus sets the "management_status" field.
func (ac *ApplicantCreate) SetManagementStatus(as applicant.ManagementStatus) *ApplicantCreate {
	ac.mutation.SetManagementStatus(as)
	return ac
}

// SetNillableManagementStatus sets the "management_status" field if the given value is not nil.
func (ac *ApplicantCreate) SetNillableManagementStatus(as *applicant.ManagementStatus) *ApplicantCreate {
	if as != nil {
		ac.SetManagementStatus(*as)
	}
	return ac
}

// SetUserID sets the "user_id" field.
func (ac *ApplicantCreate) SetUserID(s string) *ApplicantCreate {
	ac.mutation.SetUserID(s)
	return ac
}

// SetRecruitmentID sets the "recruitment_id" field.
func (ac *ApplicantCreate) SetRecruitmentID(s string) *ApplicantCreate {
	ac.mutation.SetRecruitmentID(s)
	return ac
}

// SetID sets the "id" field.
func (ac *ApplicantCreate) SetID(s string) *ApplicantCreate {
	ac.mutation.SetID(s)
	return ac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ac *ApplicantCreate) SetNillableID(s *string) *ApplicantCreate {
	if s != nil {
		ac.SetID(*s)
	}
	return ac
}

// SetUser sets the "user" edge to the User entity.
func (ac *ApplicantCreate) SetUser(u *User) *ApplicantCreate {
	return ac.SetUserID(u.ID)
}

// SetRecruitment sets the "recruitment" edge to the Recruitment entity.
func (ac *ApplicantCreate) SetRecruitment(r *Recruitment) *ApplicantCreate {
	return ac.SetRecruitmentID(r.ID)
}

// Mutation returns the ApplicantMutation object of the builder.
func (ac *ApplicantCreate) Mutation() *ApplicantMutation {
	return ac.mutation
}

// Save creates the Applicant in the database.
func (ac *ApplicantCreate) Save(ctx context.Context) (*Applicant, error) {
	var (
		err  error
		node *Applicant
	)
	ac.defaults()
	if len(ac.hooks) == 0 {
		if err = ac.check(); err != nil {
			return nil, err
		}
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ApplicantMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ac.check(); err != nil {
				return nil, err
			}
			ac.mutation = mutation
			if node, err = ac.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			if ac.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *ApplicantCreate) SaveX(ctx context.Context) *Applicant {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *ApplicantCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *ApplicantCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *ApplicantCreate) defaults() {
	if _, ok := ac.mutation.CreatedAt(); !ok {
		v := applicant.DefaultCreatedAt()
		ac.mutation.SetCreatedAt(v)
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		v := applicant.DefaultUpdatedAt()
		ac.mutation.SetUpdatedAt(v)
	}
	if _, ok := ac.mutation.ManagementStatus(); !ok {
		v := applicant.DefaultManagementStatus
		ac.mutation.SetManagementStatus(v)
	}
	if _, ok := ac.mutation.ID(); !ok {
		v := applicant.DefaultID()
		ac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *ApplicantCreate) check() error {
	if _, ok := ac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Applicant.created_at"`)}
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Applicant.updated_at"`)}
	}
	if _, ok := ac.mutation.ManagementStatus(); !ok {
		return &ValidationError{Name: "management_status", err: errors.New(`ent: missing required field "Applicant.management_status"`)}
	}
	if v, ok := ac.mutation.ManagementStatus(); ok {
		if err := applicant.ManagementStatusValidator(v); err != nil {
			return &ValidationError{Name: "management_status", err: fmt.Errorf(`ent: validator failed for field "Applicant.management_status": %w`, err)}
		}
	}
	if _, ok := ac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Applicant.user_id"`)}
	}
	if _, ok := ac.mutation.RecruitmentID(); !ok {
		return &ValidationError{Name: "recruitment_id", err: errors.New(`ent: missing required field "Applicant.recruitment_id"`)}
	}
	if v, ok := ac.mutation.ID(); ok {
		if err := applicant.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Applicant.id": %w`, err)}
		}
	}
	if _, ok := ac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Applicant.user"`)}
	}
	if _, ok := ac.mutation.RecruitmentID(); !ok {
		return &ValidationError{Name: "recruitment", err: errors.New(`ent: missing required edge "Applicant.recruitment"`)}
	}
	return nil
}

func (ac *ApplicantCreate) sqlSave(ctx context.Context) (*Applicant, error) {
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Applicant.ID type: %T", _spec.ID.Value)
		}
	}
	return _node, nil
}

func (ac *ApplicantCreate) createSpec() (*Applicant, *sqlgraph.CreateSpec) {
	var (
		_node = &Applicant{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: applicant.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: applicant.FieldID,
			},
		}
	)
	_spec.OnConflict = ac.conflict
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: applicant.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := ac.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: applicant.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := ac.mutation.ManagementStatus(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: applicant.FieldManagementStatus,
		})
		_node.ManagementStatus = value
	}
	if nodes := ac.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   applicant.UserTable,
			Columns: []string{applicant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.RecruitmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   applicant.RecruitmentTable,
			Columns: []string{applicant.RecruitmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: recruitment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RecruitmentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Applicant.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ApplicantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (ac *ApplicantCreate) OnConflict(opts ...sql.ConflictOption) *ApplicantUpsertOne {
	ac.conflict = opts
	return &ApplicantUpsertOne{
		create: ac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Applicant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (ac *ApplicantCreate) OnConflictColumns(columns ...string) *ApplicantUpsertOne {
	ac.conflict = append(ac.conflict, sql.ConflictColumns(columns...))
	return &ApplicantUpsertOne{
		create: ac,
	}
}

type (
	// ApplicantUpsertOne is the builder for "upsert"-ing
	//  one Applicant node.
	ApplicantUpsertOne struct {
		create *ApplicantCreate
	}

	// ApplicantUpsert is the "OnConflict" setter.
	ApplicantUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *ApplicantUpsert) SetCreatedAt(v time.Time) *ApplicantUpsert {
	u.Set(applicant.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ApplicantUpsert) UpdateCreatedAt() *ApplicantUpsert {
	u.SetExcluded(applicant.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ApplicantUpsert) SetUpdatedAt(v time.Time) *ApplicantUpsert {
	u.Set(applicant.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ApplicantUpsert) UpdateUpdatedAt() *ApplicantUpsert {
	u.SetExcluded(applicant.FieldUpdatedAt)
	return u
}

// SetManagementStatus sets the "management_status" field.
func (u *ApplicantUpsert) SetManagementStatus(v applicant.ManagementStatus) *ApplicantUpsert {
	u.Set(applicant.FieldManagementStatus, v)
	return u
}

// UpdateManagementStatus sets the "management_status" field to the value that was provided on create.
func (u *ApplicantUpsert) UpdateManagementStatus() *ApplicantUpsert {
	u.SetExcluded(applicant.FieldManagementStatus)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ApplicantUpsert) SetUserID(v string) *ApplicantUpsert {
	u.Set(applicant.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ApplicantUpsert) UpdateUserID() *ApplicantUpsert {
	u.SetExcluded(applicant.FieldUserID)
	return u
}

// SetRecruitmentID sets the "recruitment_id" field.
func (u *ApplicantUpsert) SetRecruitmentID(v string) *ApplicantUpsert {
	u.Set(applicant.FieldRecruitmentID, v)
	return u
}

// UpdateRecruitmentID sets the "recruitment_id" field to the value that was provided on create.
func (u *ApplicantUpsert) UpdateRecruitmentID() *ApplicantUpsert {
	u.SetExcluded(applicant.FieldRecruitmentID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Applicant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(applicant.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *ApplicantUpsertOne) UpdateNewValues() *ApplicantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(applicant.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(applicant.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.Applicant.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *ApplicantUpsertOne) Ignore() *ApplicantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ApplicantUpsertOne) DoNothing() *ApplicantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ApplicantCreate.OnConflict
// documentation for more info.
func (u *ApplicantUpsertOne) Update(set func(*ApplicantUpsert)) *ApplicantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ApplicantUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ApplicantUpsertOne) SetCreatedAt(v time.Time) *ApplicantUpsertOne {
	return u.Update(func(s *ApplicantUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ApplicantUpsertOne) UpdateCreatedAt() *ApplicantUpsertOne {
	return u.Update(func(s *ApplicantUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ApplicantUpsertOne) SetUpdatedAt(v time.Time) *ApplicantUpsertOne {
	return u.Update(func(s *ApplicantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ApplicantUpsertOne) UpdateUpdatedAt() *ApplicantUpsertOne {
	return u.Update(func(s *ApplicantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetManagementStatus sets the "management_status" field.
func (u *ApplicantUpsertOne) SetManagementStatus(v applicant.ManagementStatus) *ApplicantUpsertOne {
	return u.Update(func(s *ApplicantUpsert) {
		s.SetManagementStatus(v)
	})
}

// UpdateManagementStatus sets the "management_status" field to the value that was provided on create.
func (u *ApplicantUpsertOne) UpdateManagementStatus() *ApplicantUpsertOne {
	return u.Update(func(s *ApplicantUpsert) {
		s.UpdateManagementStatus()
	})
}

// SetUserID sets the "user_id" field.
func (u *ApplicantUpsertOne) SetUserID(v string) *ApplicantUpsertOne {
	return u.Update(func(s *ApplicantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ApplicantUpsertOne) UpdateUserID() *ApplicantUpsertOne {
	return u.Update(func(s *ApplicantUpsert) {
		s.UpdateUserID()
	})
}

// SetRecruitmentID sets the "recruitment_id" field.
func (u *ApplicantUpsertOne) SetRecruitmentID(v string) *ApplicantUpsertOne {
	return u.Update(func(s *ApplicantUpsert) {
		s.SetRecruitmentID(v)
	})
}

// UpdateRecruitmentID sets the "recruitment_id" field to the value that was provided on create.
func (u *ApplicantUpsertOne) UpdateRecruitmentID() *ApplicantUpsertOne {
	return u.Update(func(s *ApplicantUpsert) {
		s.UpdateRecruitmentID()
	})
}

// Exec executes the query.
func (u *ApplicantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ApplicantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ApplicantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ApplicantUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ApplicantUpsertOne.ID is not supported by MySQL driver. Use ApplicantUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ApplicantUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ApplicantCreateBulk is the builder for creating many Applicant entities in bulk.
type ApplicantCreateBulk struct {
	config
	builders []*ApplicantCreate
	conflict []sql.ConflictOption
}

// Save creates the Applicant entities in the database.
func (acb *ApplicantCreateBulk) Save(ctx context.Context) ([]*Applicant, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Applicant, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApplicantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = acb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *ApplicantCreateBulk) SaveX(ctx context.Context) []*Applicant {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *ApplicantCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *ApplicantCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Applicant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ApplicantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (acb *ApplicantCreateBulk) OnConflict(opts ...sql.ConflictOption) *ApplicantUpsertBulk {
	acb.conflict = opts
	return &ApplicantUpsertBulk{
		create: acb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Applicant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (acb *ApplicantCreateBulk) OnConflictColumns(columns ...string) *ApplicantUpsertBulk {
	acb.conflict = append(acb.conflict, sql.ConflictColumns(columns...))
	return &ApplicantUpsertBulk{
		create: acb,
	}
}

// ApplicantUpsertBulk is the builder for "upsert"-ing
// a bulk of Applicant nodes.
type ApplicantUpsertBulk struct {
	create *ApplicantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Applicant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(applicant.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *ApplicantUpsertBulk) UpdateNewValues() *ApplicantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(applicant.FieldID)
				return
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(applicant.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Applicant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *ApplicantUpsertBulk) Ignore() *ApplicantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ApplicantUpsertBulk) DoNothing() *ApplicantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ApplicantCreateBulk.OnConflict
// documentation for more info.
func (u *ApplicantUpsertBulk) Update(set func(*ApplicantUpsert)) *ApplicantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ApplicantUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ApplicantUpsertBulk) SetCreatedAt(v time.Time) *ApplicantUpsertBulk {
	return u.Update(func(s *ApplicantUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ApplicantUpsertBulk) UpdateCreatedAt() *ApplicantUpsertBulk {
	return u.Update(func(s *ApplicantUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ApplicantUpsertBulk) SetUpdatedAt(v time.Time) *ApplicantUpsertBulk {
	return u.Update(func(s *ApplicantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ApplicantUpsertBulk) UpdateUpdatedAt() *ApplicantUpsertBulk {
	return u.Update(func(s *ApplicantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetManagementStatus sets the "management_status" field.
func (u *ApplicantUpsertBulk) SetManagementStatus(v applicant.ManagementStatus) *ApplicantUpsertBulk {
	return u.Update(func(s *ApplicantUpsert) {
		s.SetManagementStatus(v)
	})
}

// UpdateManagementStatus sets the "management_status" field to the value that was provided on create.
func (u *ApplicantUpsertBulk) UpdateManagementStatus() *ApplicantUpsertBulk {
	return u.Update(func(s *ApplicantUpsert) {
		s.UpdateManagementStatus()
	})
}

// SetUserID sets the "user_id" field.
func (u *ApplicantUpsertBulk) SetUserID(v string) *ApplicantUpsertBulk {
	return u.Update(func(s *ApplicantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ApplicantUpsertBulk) UpdateUserID() *ApplicantUpsertBulk {
	return u.Update(func(s *ApplicantUpsert) {
		s.UpdateUserID()
	})
}

// SetRecruitmentID sets the "recruitment_id" field.
func (u *ApplicantUpsertBulk) SetRecruitmentID(v string) *ApplicantUpsertBulk {
	return u.Update(func(s *ApplicantUpsert) {
		s.SetRecruitmentID(v)
	})
}

// UpdateRecruitmentID sets the "recruitment_id" field to the value that was provided on create.
func (u *ApplicantUpsertBulk) UpdateRecruitmentID() *ApplicantUpsertBulk {
	return u.Update(func(s *ApplicantUpsert) {
		s.UpdateRecruitmentID()
	})
}

// Exec executes the query.
func (u *ApplicantUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ApplicantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ApplicantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ApplicantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
