// Code generated by entc, DO NOT EDIT.

package ent

import "context"

func (a *Applicant) User(ctx context.Context) (*User, error) {
	result, err := a.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = a.QueryUser().Only(ctx)
	}
	return result, err
}

func (a *Applicant) Recruitment(ctx context.Context) (*Recruitment, error) {
	result, err := a.Edges.RecruitmentOrErr()
	if IsNotLoaded(err) {
		result, err = a.QueryRecruitment().Only(ctx)
	}
	return result, err
}

func (c *Competition) Recruitments(ctx context.Context) ([]*Recruitment, error) {
	result, err := c.Edges.RecruitmentsOrErr()
	if IsNotLoaded(err) {
		result, err = c.QueryRecruitments().All(ctx)
	}
	return result, err
}

func (pr *Prefecture) Recruitments(ctx context.Context) ([]*Recruitment, error) {
	result, err := pr.Edges.RecruitmentsOrErr()
	if IsNotLoaded(err) {
		result, err = pr.QueryRecruitments().All(ctx)
	}
	return result, err
}

func (r *Recruitment) Stocks(ctx context.Context) ([]*Stock, error) {
	result, err := r.Edges.StocksOrErr()
	if IsNotLoaded(err) {
		result, err = r.QueryStocks().All(ctx)
	}
	return result, err
}

func (r *Recruitment) Applicants(ctx context.Context) ([]*Applicant, error) {
	result, err := r.Edges.ApplicantsOrErr()
	if IsNotLoaded(err) {
		result, err = r.QueryApplicants().All(ctx)
	}
	return result, err
}

func (r *Recruitment) User(ctx context.Context) (*User, error) {
	result, err := r.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = r.QueryUser().Only(ctx)
	}
	return result, err
}

func (r *Recruitment) Prefecture(ctx context.Context) (*Prefecture, error) {
	result, err := r.Edges.PrefectureOrErr()
	if IsNotLoaded(err) {
		result, err = r.QueryPrefecture().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (r *Recruitment) Competition(ctx context.Context) (*Competition, error) {
	result, err := r.Edges.CompetitionOrErr()
	if IsNotLoaded(err) {
		result, err = r.QueryCompetition().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (s *Stock) User(ctx context.Context) (*User, error) {
	result, err := s.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = s.QueryUser().Only(ctx)
	}
	return result, err
}

func (s *Stock) Recruitment(ctx context.Context) (*Recruitment, error) {
	result, err := s.Edges.RecruitmentOrErr()
	if IsNotLoaded(err) {
		result, err = s.QueryRecruitment().Only(ctx)
	}
	return result, err
}

func (u *User) Recruitments(ctx context.Context) ([]*Recruitment, error) {
	result, err := u.Edges.RecruitmentsOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryRecruitments().All(ctx)
	}
	return result, err
}

func (u *User) Stocks(ctx context.Context) ([]*Stock, error) {
	result, err := u.Edges.StocksOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryStocks().All(ctx)
	}
	return result, err
}

func (u *User) Applicants(ctx context.Context) ([]*Applicant, error) {
	result, err := u.Edges.ApplicantsOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryApplicants().All(ctx)
	}
	return result, err
}
