// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nagokos/connefut_backend/ent/predicate"
	"github.com/nagokos/connefut_backend/ent/recruitmenttag"
)

// RecruitmentTagDelete is the builder for deleting a RecruitmentTag entity.
type RecruitmentTagDelete struct {
	config
	hooks    []Hook
	mutation *RecruitmentTagMutation
}

// Where appends a list predicates to the RecruitmentTagDelete builder.
func (rtd *RecruitmentTagDelete) Where(ps ...predicate.RecruitmentTag) *RecruitmentTagDelete {
	rtd.mutation.Where(ps...)
	return rtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rtd *RecruitmentTagDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rtd.hooks) == 0 {
		affected, err = rtd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RecruitmentTagMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rtd.mutation = mutation
			affected, err = rtd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rtd.hooks) - 1; i >= 0; i-- {
			if rtd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rtd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rtd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtd *RecruitmentTagDelete) ExecX(ctx context.Context) int {
	n, err := rtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rtd *RecruitmentTagDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: recruitmenttag.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: recruitmenttag.FieldID,
			},
		},
	}
	if ps := rtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, rtd.driver, _spec)
}

// RecruitmentTagDeleteOne is the builder for deleting a single RecruitmentTag entity.
type RecruitmentTagDeleteOne struct {
	rtd *RecruitmentTagDelete
}

// Exec executes the deletion query.
func (rtdo *RecruitmentTagDeleteOne) Exec(ctx context.Context) error {
	n, err := rtdo.rtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{recruitmenttag.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rtdo *RecruitmentTagDeleteOne) ExecX(ctx context.Context) {
	rtdo.rtd.ExecX(ctx)
}
