// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/nagokos/connefut_backend/ent/recruitment"
)

// Recruitment is the model entity for the Recruitment schema.
type Recruitment struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Type holds the value of the "type" field.
	Type recruitment.Type `json:"type,omitempty"`
	// Place holds the value of the "place" field.
	Place string `json:"place,omitempty"`
	// StartAt holds the value of the "start_at" field.
	StartAt time.Time `json:"start_at,omitempty"`
	// Content holds the value of the "content" field.
	// 募集詳細
	Content string `json:"content,omitempty"`
	// LocationURL holds the value of the "Location_url" field.
	// 会場の場所を埋め込むURL
	LocationURL string `json:"Location_url,omitempty"`
	// Capacity holds the value of the "capacity" field.
	Capacity int `json:"capacity,omitempty"`
	// ClosingAt holds the value of the "closing_at" field.
	// 募集期限
	ClosingAt time.Time `json:"closing_at,omitempty"`
	user_id   *string
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Recruitment) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case recruitment.FieldCapacity:
			values[i] = new(sql.NullInt64)
		case recruitment.FieldID, recruitment.FieldTitle, recruitment.FieldType, recruitment.FieldPlace, recruitment.FieldContent, recruitment.FieldLocationURL:
			values[i] = new(sql.NullString)
		case recruitment.FieldCreatedAt, recruitment.FieldUpdatedAt, recruitment.FieldStartAt, recruitment.FieldClosingAt:
			values[i] = new(sql.NullTime)
		case recruitment.ForeignKeys[0]: // user_id
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Recruitment", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Recruitment fields.
func (r *Recruitment) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recruitment.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				r.ID = value.String
			}
		case recruitment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				r.CreatedAt = value.Time
			}
		case recruitment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				r.UpdatedAt = value.Time
			}
		case recruitment.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				r.Title = value.String
			}
		case recruitment.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				r.Type = recruitment.Type(value.String)
			}
		case recruitment.FieldPlace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field place", values[i])
			} else if value.Valid {
				r.Place = value.String
			}
		case recruitment.FieldStartAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_at", values[i])
			} else if value.Valid {
				r.StartAt = value.Time
			}
		case recruitment.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				r.Content = value.String
			}
		case recruitment.FieldLocationURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Location_url", values[i])
			} else if value.Valid {
				r.LocationURL = value.String
			}
		case recruitment.FieldCapacity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field capacity", values[i])
			} else if value.Valid {
				r.Capacity = int(value.Int64)
			}
		case recruitment.FieldClosingAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closing_at", values[i])
			} else if value.Valid {
				r.ClosingAt = value.Time
			}
		case recruitment.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				r.user_id = new(string)
				*r.user_id = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Recruitment.
// Note that you need to call Recruitment.Unwrap() before calling this method if this Recruitment
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Recruitment) Update() *RecruitmentUpdateOne {
	return (&RecruitmentClient{config: r.config}).UpdateOne(r)
}

// Unwrap unwraps the Recruitment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Recruitment) Unwrap() *Recruitment {
	tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Recruitment is not a transactional entity")
	}
	r.config.driver = tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Recruitment) String() string {
	var builder strings.Builder
	builder.WriteString("Recruitment(")
	builder.WriteString(fmt.Sprintf("id=%v", r.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(r.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(r.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", title=")
	builder.WriteString(r.Title)
	builder.WriteString(", type=")
	builder.WriteString(fmt.Sprintf("%v", r.Type))
	builder.WriteString(", place=")
	builder.WriteString(r.Place)
	builder.WriteString(", start_at=")
	builder.WriteString(r.StartAt.Format(time.ANSIC))
	builder.WriteString(", content=")
	builder.WriteString(r.Content)
	builder.WriteString(", Location_url=")
	builder.WriteString(r.LocationURL)
	builder.WriteString(", capacity=")
	builder.WriteString(fmt.Sprintf("%v", r.Capacity))
	builder.WriteString(", closing_at=")
	builder.WriteString(r.ClosingAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Recruitments is a parsable slice of Recruitment.
type Recruitments []*Recruitment

func (r Recruitments) config(cfg config) {
	for _i := range r {
		r[_i].config = cfg
	}
}
