// Code generated by entc, DO NOT EDIT.

package prefecture

import (
	"time"
)

const (
	// Label holds the string label denoting the prefecture type in the database.
	Label = "prefecture"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeRecruitments holds the string denoting the recruitments edge name in mutations.
	EdgeRecruitments = "recruitments"
	// Table holds the table name of the prefecture in the database.
	Table = "prefectures"
	// RecruitmentsTable is the table that holds the recruitments relation/edge.
	RecruitmentsTable = "recruitments"
	// RecruitmentsInverseTable is the table name for the Recruitment entity.
	// It exists in this package in order to avoid circular dependency with the "recruitment" package.
	RecruitmentsInverseTable = "recruitments"
	// RecruitmentsColumn is the table column denoting the recruitments relation/edge.
	RecruitmentsColumn = "prefecture_id"
)

// Columns holds all SQL columns for prefecture fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)
