name: Go

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: check out
      uses: actions/checkout@v2
    
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: check out
      uses: actions/checkout@v2
    - name: build
      run: go build -v ./...

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: lint
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1"

  slack-notification:
    if: always()
    runs-on: ubuntu-latest
    needs: [setup, build, lint]
    steps:
    - name: slack - GitHub Actions Slack integration
      uses: act10ns/slack@v1.5.0
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
