name: Go

on: [push]

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_CHANNEL: actions_backend
  SLACK_ICON: https://example.com/image/icon_bot.png

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: check out
      uses: actions/checkout@v2
    
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: check out
      uses: actions/checkout@v2
    - name: build
      run: go build -v ./...

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: lint
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1"

  slack_notification:
    if: success()
    runs-on: ubuntu-latest
    needs: [setup, build, lint]
    steps:
    - name: check out
      uses: actions/checkout@v2
    - name: success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: good
        SLACK_MESSAGE: Success!!
        SLACK_TITLE: Message
    - name: failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: danger
        SLACK_MESSAGE: Failure!!
        SLACK_TITLE: Message
   
