name: Go

on: [push]

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_CHANNEL: actions_backend
  SLACK_ICON: https://s3-us-west-2.amazonaws.com/slack-files2/bot_icons/2022-01-03/2916535299873_48.png
  SLACK_USERNAME: Github Actions

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: check out
      uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: check out
      uses: actions/checkout@v3
    - name: build
      run: go build -v ./...

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: check out
      uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.29

  notification_success:
    if: success()
    runs-on: ubuntu-latest
    needs: [setup, build, lint]
    steps:
    - name: check out
      uses: actions/checkout@v3
    - name: success
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: good
        SLACK_MESSAGE: Success in all workflows!!
        SLACK_TITLE: Message

  notification_failure:
    if: failure()
    runs-on: ubuntu-latest
    needs: [setup, build, lint]
    steps:
    - name: check out
      uses: actions/checkout@v3
    - name: failure
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: danger
        SLACK_MESSAGE: Workflow Failure!!
        SLACK_TITLE: Message
   
